import type { SubscriptionPlan, AddOn } from "@/types/api"

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "basic-plan",
    name: "Basic Plan",
    description: "Perfect for individuals - simple and affordable",
    weeklyPrice: "50.00",
    monthlyPrice: "200.00",
    mealsPerWeek: 5,
    features: [
      "1 meal per day (Lunch or Dinner)",
      "Monday to Friday delivery",
      "4 rotis + 1 veg curry + rice + raita",
      "Free delivery in Mississauga & Brampton",
      "Cancel anytime",
      "Email & WhatsApp support",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "regular-plan",
    name: "Regular Plan",
    description: "Most popular - great value for daily meals",
    weeklyPrice: "65.00",
    monthlyPrice: "260.00",
    mealsPerWeek: 5,
    features: [
      "1 meal per day (Lunch or Dinner)",
      "Monday to Friday delivery",
      "6 rotis + 1 veg curry + 1 non-veg curry + rice + raita",
      "Free delivery in Mississauga & Brampton",
      "Dietary preferences (veg/non-veg)",
      "Priority WhatsApp support",
      "Cancel anytime",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "family-plan",
    name: "Family Plan",
    description: "Perfect for families - 2 meals daily",
    weeklyPrice: "95.00",
    monthlyPrice: "380.00",
    mealsPerWeek: 10,
    features: [
      "2 meals per day (Lunch & Dinner)",
      "Monday to Friday delivery",
      "8 rotis + 2 curries + rice + raita + seasonal veg",
      "Mix of veg & non-veg options",
      "Free delivery in Mississauga & Brampton",
      "Custom dietary preferences",
      "Priority WhatsApp support",
      "Weekend meal add-on available",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "deluxe-plan",
    name: "Deluxe Plan",
    description: "Ultimate experience - 7 days with extras",
    weeklyPrice: "120.00",
    monthlyPrice: "480.00",
    mealsPerWeek: 14,
    features: [
      "2 meals per day (Lunch & Dinner)",
      "7 days a week delivery (including weekends)",
      "10 rotis + 2 curries + rice + raita + salad + dessert",
      "Premium veg & non-veg variety",
      "Free delivery across GTA",
      "Custom menu planning",
      "24/7 phone support",
      "Special festival meals",
      "Pause/resume anytime",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockAddOns: AddOn[] = [
  {
    id: "extra-roti",
    name: "Extra Roti/Naan (2 pcs)",
    description: "Add 2 pieces of fresh roti or naan to your meal",
    weeklyPrice: "8.00",
    monthlyPrice: "30.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dessert",
    name: "Dessert of the Day",
    description: "Sweet treat to complete your meal - Gulab Jamun, Kheer, or Rasmalai",
    weeklyPrice: "15.00",
    monthlyPrice: "55.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "extra-dal",
    name: "Extra Dal/Curry",
    description: "Additional serving of dal or vegetable curry",
    weeklyPrice: "12.00",
    monthlyPrice: "45.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "beverage",
    name: "Beverage (Mango Lassi or Chai)",
    description: "Refreshing mango lassi or traditional masala chai",
    weeklyPrice: "10.00",
    monthlyPrice: "35.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
