import type { SubscriptionPlan, AddOn } from "@/types/api"

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "basic-plan",
    name: "Basic Plan",
    description: "Perfect for individuals - 1 meal per day",
    weeklyPrice: "699.00",
    monthlyPrice: "2499.00",
    mealsPerWeek: 6,
    features: [
      "1 meal per day (Lunch or Dinner)",
      "6 days a week delivery",
      "Free delivery",
      "Cancel anytime",
      "Email support",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "premium-plan",
    name: "Premium Plan",
    description: "Best for families - 2 meals per day",
    weeklyPrice: "1249.00",
    monthlyPrice: "4999.00",
    mealsPerWeek: 14,
    features: [
      "2 meals per day (Lunch & Dinner)",
      "7 days a week delivery",
      "Free delivery & packaging",
      "Custom menu preferences",
      "Priority support 24/7",
      "Special festival menus",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockAddOns: AddOn[] = [
  {
    id: "extra-roti",
    name: "Extra Roti/Naan (2 pcs)",
    description: "Add 2 pieces of fresh roti or naan to your meal",
    weeklyPrice: "50.00",
    monthlyPrice: "200.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dessert",
    name: "Dessert of the Day",
    description: "Sweet treat to complete your meal - Gulab Jamun, Kheer, or Rasmalai",
    weeklyPrice: "120.00",
    monthlyPrice: "480.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "extra-dal",
    name: "Extra Dal/Curry",
    description: "Additional serving of dal or vegetable curry",
    weeklyPrice: "80.00",
    monthlyPrice: "320.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "beverage",
    name: "Beverage (Mango Lassi or Chai)",
    description: "Refreshing mango lassi or traditional masala chai",
    weeklyPrice: "60.00",
    monthlyPrice: "240.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
