import type { SubscriptionPlan, AddOn } from "@/types/api"

export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: "essential-plan",
    name: "Essential Plan",
    description: "Perfect for individuals - 1 meal per day, Mon-Fri",
    weeklyPrice: "55.00",
    monthlyPrice: "220.00",
    mealsPerWeek: 5,
    features: [
      "1 meal per day (Lunch or Dinner)",
      "Monday to Friday delivery",
      "Free delivery in Mississauga & Brampton",
      "4 rotis + 1 curry + rice",
      "Cancel anytime",
      "Email support",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "family-plan",
    name: "Family Plan",
    description: "Best for families - 2 meals per day, Mon-Fri",
    weeklyPrice: "95.00",
    monthlyPrice: "380.00",
    mealsPerWeek: 10,
    features: [
      "2 meals per day (Lunch & Dinner)",
      "Monday to Friday delivery",
      "Free delivery in Mississauga & Brampton",
      "6 rotis + 2 curries + rice + extras",
      "Custom dietary preferences",
      "Priority WhatsApp support",
      "Weekend meal options available",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "premium-plan",
    name: "Premium Plan",
    description: "Ultimate convenience - 7 days a week",
    weeklyPrice: "120.00",
    monthlyPrice: "480.00",
    mealsPerWeek: 14,
    features: [
      "2 meals per day (Lunch & Dinner)",
      "7 days a week delivery (including weekends)",
      "Free delivery across GTA",
      "8 rotis + 2 curries + rice + sides + dessert",
      "Custom menu planning",
      "24/7 phone support",
      "Special occasion meals",
      "Pause/resume anytime",
    ],
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const mockAddOns: AddOn[] = [
  {
    id: "extra-roti",
    name: "Extra Roti/Naan (2 pcs)",
    description: "Add 2 pieces of fresh roti or naan to your meal",
    weeklyPrice: "8.00",
    monthlyPrice: "30.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dessert",
    name: "Dessert of the Day",
    description: "Sweet treat to complete your meal - Gulab Jamun, Kheer, or Rasmalai",
    weeklyPrice: "15.00",
    monthlyPrice: "55.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "extra-dal",
    name: "Extra Dal/Curry",
    description: "Additional serving of dal or vegetable curry",
    weeklyPrice: "12.00",
    monthlyPrice: "45.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "beverage",
    name: "Beverage (Mango Lassi or Chai)",
    description: "Refreshing mango lassi or traditional masala chai",
    weeklyPrice: "10.00",
    monthlyPrice: "35.00",
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
